services:

  jaeger-query:
    image: jaegertracing/jaeger-query:1.38
    stop_grace_period: 10s
    ports:
    - "16686:16686" # web UI
    - "16687"
    depends_on:
    - jaeger-influxdb
    environment:
      #QUERY_BEARER_TOKEN_PROPAGATION: true
      LOG_LEVEL: warn
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: jaeger-influxdb:17271
      GRPC_STORAGE_CONNECTION_TIMEOUT: 30s
      QUERY_HTTP_SERVER_HOST_PORT: :16686
      ADMIN_HTTP_HOST_PORT: :16687

  jaeger-influxdb:
    build:
      context: .
      dockerfile: jaeger-query-plugin/Dockerfile
    image: jaeger-influxdb:local
    stop_grace_period: 10s
    environment:
      LOG_LEVEL: info
      LISTEN_ADDR: :17271
      INFLUXDB_TIMEOUT: 30s
      # required: hostname or hostname:port
      INFLUXDB_ADDR:
      # required: either BUCKETID or BUCKETNAME
      INFLUXDB_BUCKETID:
      INFLUXDB_BUCKETNAME:
      # required
      INFLUXDB_TOKEN:

  hotrod:
    image: jaegertracing/example-hotrod:1.38
    command: ["all"]
    stop_grace_period: 1s
    ports:
    - "8080:8080" # web UI
    depends_on:
    - otelcol
    environment:
      JAEGER_AGENT_HOST: otelcol
      JAEGER_AGENT_PORT: 6831

  otelcol:
    build:
      context: .
      dockerfile: otelcol-influxdb/Dockerfile
    image: otelcol-influxdb:local
    command: ["--config", "/config.yml"]
    stop_grace_period: 10s
    volumes:
    - ./otelcol-influxdb/config.yml:/config.yml:ro
