dist:
  name: otelcol-influxdb
  module: github.com/influxdata/influxdb-observability/otelcol-influxdb
  description: OpenTelemetry Collector Distribution built for InfluxDB
  version: 0.101.0-0.0.0-beta.0
  otelcol_version: 0.101.0
  output_path: ./build

receivers:
- gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkametricsreceiver v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.101.0

exporters:
- gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter v0.101.0

connectors:
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector v0.101.0

extensions:
- gomod: go.opentelemetry.io/collector/extension/ballastextension v0.101.0
- gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.101.0

processors:
- gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.101.0
- gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.101.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.101.0

replaces:
- github.com/influxdata/influxdb-observability/common => ../../common
- github.com/influxdata/influxdb-observability/influx2otel => ../../influx2otel
- github.com/influxdata/influxdb-observability/otel2influx => ../../otel2influx
