{
 "title": "Open Telemetry",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Service", "label": "Service", "query": "redis" },
   { "name": "TraceID", "label": "TraceID", "query": "120011cb7f5fefbd" }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT DISTINCT(\"service.name\") FROM \"spans\" WHERE $__timeRange(time)"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \"duration_nano\"/ 1000000 as \"duration\", \"span_id\" ,time FROM \"spans\" WHERE $__timeRange(time) AND \"service.name\" = '$Service' order by time"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  (COUNT(CASE WHEN \"otel.status_code\" = 'Error' THEN 1 END) * 100.0) / COUNT(*) as error_percentage FROM spans\n  WHERE $__timeRange(time) AND \"service.name\" = '$Service' "
    }
   ]
  },
  {
   "title": "Service Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 8 },
   "targets": [
    { "service": "$Service" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "targets": [
    { "service": "$Service" }
   ]
  },
  {
   "title": "Relationships ",
   "type": "nodeGraph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 13 },
   "targets": [
    { "query": "$TraceID" }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "query": "$TraceID" }
   ]
  }
 ]
}