{
 "title": "Open Telemetry",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Service", "label": "Service", "query": "redis" },
   { "name": "TraceID", "label": "TraceID", "query": "120011cb7f5fefbd" }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT DISTINCT(\"service.name\") FROM \"spans\" WHERE $__timeRange(time)"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \"duration_nano\", \"span_id\" ,time FROM \"spans\" WHERE $__timeRange(time) AND \"service.name\" = '$Service' order by time"
    }
   ]
  },
  {
   "title": "Service Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 7 },
   "targets": [
    { "service": "$Service" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 17 },
   "targets": [
    { "service": "$Service" }
   ]
  },
  {
   "title": "Relationships ",
   "type": "nodeGraph",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 17 },
   "targets": [
    { "query": "$TraceID" }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "query": "$TraceID" }
   ]
  }
 ]
}