FROM golang:1.16-alpine AS builder

RUN apk add git
RUN git clone --branch master --depth 1 https://github.com/influxdata/telegraf
WORKDIR /go/telegraf

RUN \
  --mount=type=cache,id=opentelemetry-collector-contrib-influxdb-gocache,sharing=locked,target=/root/.cache/go-build \
  --mount=type=cache,id=opentelemetry-collector-contrib-influxdb-gomodcache,sharing=locked,target=/go/pkg/mod \
  CGO_ENABLED=0 go install ./cmd/telegraf

FROM scratch

COPY --from=builder /go/bin/telegraf /
CMD ["/telegraf"]
