// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opentelemetry/proto/metrics/experimental/metrics_config_service.proto

package experimental

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	v1 "github.com/influxdata/influxdb-observability/otlp/resource/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MetricConfigRequest struct {
	// Required. The resource for which configuration should be returned.
	Resource *v1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Optional. The value of MetricConfigResponse.fingerprint for the last
	// configuration that the caller received and successfully applied.
	LastKnownFingerprint []byte   `protobuf:"bytes,2,opt,name=last_known_fingerprint,json=lastKnownFingerprint,proto3" json:"last_known_fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricConfigRequest) Reset()         { *m = MetricConfigRequest{} }
func (m *MetricConfigRequest) String() string { return proto.CompactTextString(m) }
func (*MetricConfigRequest) ProtoMessage()    {}
func (*MetricConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd5f5955cb59f8ef, []int{0}
}
func (m *MetricConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricConfigRequest.Unmarshal(m, b)
}
func (m *MetricConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricConfigRequest.Marshal(b, m, deterministic)
}
func (m *MetricConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricConfigRequest.Merge(m, src)
}
func (m *MetricConfigRequest) XXX_Size() int {
	return xxx_messageInfo_MetricConfigRequest.Size(m)
}
func (m *MetricConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricConfigRequest proto.InternalMessageInfo

func (m *MetricConfigRequest) GetResource() *v1.Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *MetricConfigRequest) GetLastKnownFingerprint() []byte {
	if m != nil {
		return m.LastKnownFingerprint
	}
	return nil
}

type MetricConfigResponse struct {
	// Optional. The fingerprint associated with this MetricConfigResponse. Each
	// change in configs yields a different fingerprint. The resource SHOULD copy
	// this value to MetricConfigRequest.last_known_fingerprint for the next
	// configuration request. If there are no changes between fingerprint and
	// MetricConfigRequest.last_known_fingerprint, then all other fields besides
	// fingerprint in the response are optional, or the same as the last update if
	// present.
	//
	// The exact mechanics of generating the fingerprint is up to the
	// implementation. However, a fingerprint must be deterministically determined
	// by the configurations -- the same configuration will generate the same
	// fingerprint on any instance of an implementation. Hence using a timestamp is
	// unacceptable, but a deterministic hash is fine.
	Fingerprint []byte `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// A single metric may match multiple schedules. In such cases, the schedule
	// that specifies the smallest period is applied.
	//
	// Note, for optimization purposes, it is recommended to use as few schedules
	// as possible to capture all required metric updates. Where you can be
	// conservative, do take full advantage of the inclusion/exclusion patterns to
	// capture as much of your targeted metrics.
	Schedules []*MetricConfigResponse_Schedule `protobuf:"bytes,2,rep,name=schedules,proto3" json:"schedules,omitempty"`
	// Optional. The client is suggested to wait this long (in seconds) before
	// pinging the configuration service again.
	SuggestedWaitTimeSec int32    `protobuf:"varint,3,opt,name=suggested_wait_time_sec,json=suggestedWaitTimeSec,proto3" json:"suggested_wait_time_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricConfigResponse) Reset()         { *m = MetricConfigResponse{} }
func (m *MetricConfigResponse) String() string { return proto.CompactTextString(m) }
func (*MetricConfigResponse) ProtoMessage()    {}
func (*MetricConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd5f5955cb59f8ef, []int{1}
}
func (m *MetricConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricConfigResponse.Unmarshal(m, b)
}
func (m *MetricConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricConfigResponse.Marshal(b, m, deterministic)
}
func (m *MetricConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricConfigResponse.Merge(m, src)
}
func (m *MetricConfigResponse) XXX_Size() int {
	return xxx_messageInfo_MetricConfigResponse.Size(m)
}
func (m *MetricConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricConfigResponse proto.InternalMessageInfo

func (m *MetricConfigResponse) GetFingerprint() []byte {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

func (m *MetricConfigResponse) GetSchedules() []*MetricConfigResponse_Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

func (m *MetricConfigResponse) GetSuggestedWaitTimeSec() int32 {
	if m != nil {
		return m.SuggestedWaitTimeSec
	}
	return 0
}

// A Schedule is used to apply a particular scheduling configuration to
// a metric. If a metric name matches a schedule's patterns, then the metric
// adopts the configuration specified by the schedule.
type MetricConfigResponse_Schedule struct {
	// Metrics with names that match a rule in the inclusion_patterns are
	// targeted by this schedule. Metrics that match the exclusion_patterns
	// are not targeted for this schedule, even if they match an inclusion
	// pattern.
	ExclusionPatterns []*MetricConfigResponse_Schedule_Pattern `protobuf:"bytes,1,rep,name=exclusion_patterns,json=exclusionPatterns,proto3" json:"exclusion_patterns,omitempty"`
	InclusionPatterns []*MetricConfigResponse_Schedule_Pattern `protobuf:"bytes,2,rep,name=inclusion_patterns,json=inclusionPatterns,proto3" json:"inclusion_patterns,omitempty"`
	// Describes the collection period for each metric in seconds.
	// A period of 0 means to not export.
	PeriodSec            int32    `protobuf:"varint,3,opt,name=period_sec,json=periodSec,proto3" json:"period_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricConfigResponse_Schedule) Reset()         { *m = MetricConfigResponse_Schedule{} }
func (m *MetricConfigResponse_Schedule) String() string { return proto.CompactTextString(m) }
func (*MetricConfigResponse_Schedule) ProtoMessage()    {}
func (*MetricConfigResponse_Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd5f5955cb59f8ef, []int{1, 0}
}
func (m *MetricConfigResponse_Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricConfigResponse_Schedule.Unmarshal(m, b)
}
func (m *MetricConfigResponse_Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricConfigResponse_Schedule.Marshal(b, m, deterministic)
}
func (m *MetricConfigResponse_Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricConfigResponse_Schedule.Merge(m, src)
}
func (m *MetricConfigResponse_Schedule) XXX_Size() int {
	return xxx_messageInfo_MetricConfigResponse_Schedule.Size(m)
}
func (m *MetricConfigResponse_Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricConfigResponse_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_MetricConfigResponse_Schedule proto.InternalMessageInfo

func (m *MetricConfigResponse_Schedule) GetExclusionPatterns() []*MetricConfigResponse_Schedule_Pattern {
	if m != nil {
		return m.ExclusionPatterns
	}
	return nil
}

func (m *MetricConfigResponse_Schedule) GetInclusionPatterns() []*MetricConfigResponse_Schedule_Pattern {
	if m != nil {
		return m.InclusionPatterns
	}
	return nil
}

func (m *MetricConfigResponse_Schedule) GetPeriodSec() int32 {
	if m != nil {
		return m.PeriodSec
	}
	return 0
}

// A light-weight pattern that can match 1 or more
// metrics, for which this schedule will apply. The string is used to
// match against metric names. It should not exceed 100k characters.
type MetricConfigResponse_Schedule_Pattern struct {
	// Types that are valid to be assigned to Match:
	//	*MetricConfigResponse_Schedule_Pattern_Equals
	//	*MetricConfigResponse_Schedule_Pattern_StartsWith
	Match                isMetricConfigResponse_Schedule_Pattern_Match `protobuf_oneof:"match"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *MetricConfigResponse_Schedule_Pattern) Reset()         { *m = MetricConfigResponse_Schedule_Pattern{} }
func (m *MetricConfigResponse_Schedule_Pattern) String() string { return proto.CompactTextString(m) }
func (*MetricConfigResponse_Schedule_Pattern) ProtoMessage()    {}
func (*MetricConfigResponse_Schedule_Pattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd5f5955cb59f8ef, []int{1, 0, 0}
}
func (m *MetricConfigResponse_Schedule_Pattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricConfigResponse_Schedule_Pattern.Unmarshal(m, b)
}
func (m *MetricConfigResponse_Schedule_Pattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricConfigResponse_Schedule_Pattern.Marshal(b, m, deterministic)
}
func (m *MetricConfigResponse_Schedule_Pattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricConfigResponse_Schedule_Pattern.Merge(m, src)
}
func (m *MetricConfigResponse_Schedule_Pattern) XXX_Size() int {
	return xxx_messageInfo_MetricConfigResponse_Schedule_Pattern.Size(m)
}
func (m *MetricConfigResponse_Schedule_Pattern) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricConfigResponse_Schedule_Pattern.DiscardUnknown(m)
}

var xxx_messageInfo_MetricConfigResponse_Schedule_Pattern proto.InternalMessageInfo

type isMetricConfigResponse_Schedule_Pattern_Match interface {
	isMetricConfigResponse_Schedule_Pattern_Match()
}

type MetricConfigResponse_Schedule_Pattern_Equals struct {
	Equals string `protobuf:"bytes,1,opt,name=equals,proto3,oneof" json:"equals,omitempty"`
}
type MetricConfigResponse_Schedule_Pattern_StartsWith struct {
	StartsWith string `protobuf:"bytes,2,opt,name=starts_with,json=startsWith,proto3,oneof" json:"starts_with,omitempty"`
}

func (*MetricConfigResponse_Schedule_Pattern_Equals) isMetricConfigResponse_Schedule_Pattern_Match() {
}
func (*MetricConfigResponse_Schedule_Pattern_StartsWith) isMetricConfigResponse_Schedule_Pattern_Match() {
}

func (m *MetricConfigResponse_Schedule_Pattern) GetMatch() isMetricConfigResponse_Schedule_Pattern_Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *MetricConfigResponse_Schedule_Pattern) GetEquals() string {
	if x, ok := m.GetMatch().(*MetricConfigResponse_Schedule_Pattern_Equals); ok {
		return x.Equals
	}
	return ""
}

func (m *MetricConfigResponse_Schedule_Pattern) GetStartsWith() string {
	if x, ok := m.GetMatch().(*MetricConfigResponse_Schedule_Pattern_StartsWith); ok {
		return x.StartsWith
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetricConfigResponse_Schedule_Pattern) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetricConfigResponse_Schedule_Pattern_Equals)(nil),
		(*MetricConfigResponse_Schedule_Pattern_StartsWith)(nil),
	}
}

func init() {
	proto.RegisterType((*MetricConfigRequest)(nil), "internal.opentelemetry.proto.metrics.experimental.MetricConfigRequest")
	proto.RegisterType((*MetricConfigResponse)(nil), "internal.opentelemetry.proto.metrics.experimental.MetricConfigResponse")
	proto.RegisterType((*MetricConfigResponse_Schedule)(nil), "internal.opentelemetry.proto.metrics.experimental.MetricConfigResponse.Schedule")
	proto.RegisterType((*MetricConfigResponse_Schedule_Pattern)(nil), "internal.opentelemetry.proto.metrics.experimental.MetricConfigResponse.Schedule.Pattern")
}

func init() {
	proto.RegisterFile("opentelemetry/proto/metrics/experimental/metrics_config_service.proto", fileDescriptor_fd5f5955cb59f8ef)
}

var fileDescriptor_fd5f5955cb59f8ef = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x9d, 0xd6, 0xfd, 0xd3, 0xe9, 0x82, 0x38, 0x16, 0x0d, 0x05, 0xa1, 0xee, 0x55, 0x6f,
	0x9c, 0xd0, 0xba, 0xbe, 0x40, 0xc5, 0xae, 0x20, 0x6a, 0x49, 0x85, 0x15, 0x6f, 0xc2, 0x34, 0x3d,
	0x6d, 0x06, 0x93, 0x99, 0x6c, 0xe6, 0xa4, 0xed, 0x3e, 0x81, 0x77, 0x3e, 0x80, 0xde, 0xf9, 0x0a,
	0xbe, 0x98, 0x8f, 0x20, 0x99, 0xa4, 0xd9, 0x14, 0x8b, 0xb0, 0xb8, 0x7b, 0x77, 0x72, 0xbe, 0x99,
	0xdf, 0xf7, 0x71, 0x98, 0x1c, 0xfa, 0x5a, 0x27, 0xa0, 0x10, 0x22, 0x88, 0x01, 0xd3, 0x2b, 0x37,
	0x49, 0x35, 0x6a, 0x37, 0xaf, 0x65, 0x60, 0x5c, 0xd8, 0x24, 0x90, 0xca, 0x18, 0x14, 0x8a, 0x68,
	0xdb, 0xf4, 0x03, 0xad, 0x16, 0x72, 0xe9, 0x1b, 0x48, 0x57, 0x32, 0x00, 0x6e, 0x6f, 0xb0, 0x81,
	0x54, 0x08, 0xa9, 0x12, 0x11, 0xdf, 0xe1, 0x15, 0x2a, 0x2f, 0xaf, 0xf2, 0x3a, 0xaf, 0xcb, 0xf7,
	0x39, 0xa7, 0x60, 0x74, 0x96, 0x06, 0xe0, 0xae, 0x06, 0x55, 0x5d, 0x40, 0x4e, 0x7f, 0x10, 0xfa,
	0xe8, 0x9d, 0x05, 0xbd, 0xb2, 0x09, 0x3c, 0xb8, 0xcc, 0xc0, 0x20, 0x7b, 0x4f, 0x8f, 0xb7, 0x27,
	0x1d, 0xd2, 0x23, 0xfd, 0xf6, 0x70, 0xc8, 0xff, 0x99, 0xa6, 0xe2, 0xae, 0x06, 0xdc, 0x2b, 0x6b,
	0xaf, 0x62, 0xb0, 0x33, 0xfa, 0x38, 0x12, 0x06, 0xfd, 0x2f, 0x4a, 0xaf, 0x95, 0xbf, 0x90, 0x6a,
	0x09, 0x69, 0x92, 0x4a, 0x85, 0x4e, 0xa3, 0x47, 0xfa, 0x27, 0x5e, 0x27, 0x57, 0xdf, 0xe6, 0xe2,
	0xf8, 0x5a, 0x3b, 0xfd, 0x7d, 0x9f, 0x76, 0x76, 0xd3, 0x99, 0x44, 0x2b, 0x03, 0xac, 0x47, 0xdb,
	0x75, 0x06, 0xb1, 0x8c, 0x7a, 0x8b, 0x29, 0xda, 0x32, 0x41, 0x08, 0xf3, 0x2c, 0x02, 0xe3, 0x34,
	0x7a, 0xcd, 0x7e, 0x7b, 0x38, 0xe1, 0x37, 0x9e, 0x27, 0xdf, 0xe7, 0xce, 0xa7, 0x25, 0xd8, 0xbb,
	0xb6, 0x60, 0x2f, 0xe9, 0x13, 0x93, 0x2d, 0x97, 0x60, 0x10, 0xe6, 0xfe, 0x5a, 0x48, 0xf4, 0x51,
	0xc6, 0xe0, 0x1b, 0x08, 0x9c, 0x66, 0x8f, 0xf4, 0x0f, 0xbc, 0x4e, 0x25, 0x5f, 0x08, 0x89, 0x1f,
	0x65, 0x0c, 0x53, 0x08, 0xba, 0xdf, 0x9a, 0xf4, 0x78, 0x8b, 0x63, 0x5f, 0x09, 0x65, 0xb0, 0x09,
	0xa2, 0xcc, 0x48, 0xad, 0xfc, 0x44, 0x60, 0x9e, 0xd6, 0x38, 0xc4, 0xa6, 0xff, 0x74, 0xdb, 0xe9,
	0xf9, 0xa4, 0x30, 0xf0, 0x1e, 0x56, 0x9e, 0x65, 0xc7, 0xd8, 0x24, 0x52, 0xfd, 0x95, 0xa4, 0x71,
	0xd7, 0x49, 0x2a, 0xcf, 0x2a, 0xc9, 0x53, 0x4a, 0x73, 0x8c, 0x9e, 0xd7, 0x46, 0xd9, 0x2a, 0x3a,
	0xf9, 0xfc, 0x3e, 0xd0, 0xa3, 0xf2, 0x28, 0x73, 0xe8, 0x21, 0x5c, 0x66, 0x22, 0x32, 0xf6, 0x39,
	0xb4, 0xde, 0xdc, 0xf3, 0xca, 0x6f, 0xf6, 0x8c, 0xb6, 0x0d, 0x8a, 0x14, 0x8d, 0xbf, 0x96, 0x18,
	0xda, 0x17, 0x97, 0xcb, 0xb4, 0x68, 0x5e, 0x48, 0x0c, 0x47, 0x47, 0xf4, 0x20, 0x16, 0x18, 0x84,
	0xc3, 0x5f, 0x84, 0x9e, 0xd4, 0xc3, 0xb2, 0x9f, 0x84, 0x3e, 0x38, 0x07, 0xdc, 0xe9, 0x8d, 0xff,
	0x7b, 0x02, 0xf6, 0x2f, 0xeb, 0x9e, 0xdf, 0xd2, 0x24, 0x47, 0xdf, 0x09, 0x3d, 0x93, 0xfa, 0xe6,
	0xb4, 0x91, 0x53, 0xc7, 0x4d, 0x8b, 0xed, 0x33, 0xc9, 0x8f, 0x4f, 0xc8, 0xe7, 0xf1, 0x52, 0x62,
	0x98, 0xcd, 0x78, 0xa0, 0x63, 0x57, 0xaa, 0x45, 0x94, 0x6d, 0xe6, 0x02, 0xc5, 0xb6, 0x9c, 0x3d,
	0xd7, 0xb3, 0x7c, 0x5d, 0x89, 0x99, 0x8c, 0x24, 0x5e, 0xb9, 0x1a, 0xa3, 0x64, 0xef, 0x8e, 0x9b,
	0x1d, 0x5a, 0xff, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x5a, 0xaa, 0x29, 0x16, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricConfigClient is the client API for MetricConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricConfigClient interface {
	GetMetricConfig(ctx context.Context, in *MetricConfigRequest, opts ...grpc.CallOption) (*MetricConfigResponse, error)
}

type metricConfigClient struct {
	cc *grpc.ClientConn
}

func NewMetricConfigClient(cc *grpc.ClientConn) MetricConfigClient {
	return &metricConfigClient{cc}
}

func (c *metricConfigClient) GetMetricConfig(ctx context.Context, in *MetricConfigRequest, opts ...grpc.CallOption) (*MetricConfigResponse, error) {
	out := new(MetricConfigResponse)
	err := c.cc.Invoke(ctx, "/internal.opentelemetry.proto.metrics.experimental.MetricConfig/GetMetricConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricConfigServer is the server API for MetricConfig service.
type MetricConfigServer interface {
	GetMetricConfig(context.Context, *MetricConfigRequest) (*MetricConfigResponse, error)
}

// UnimplementedMetricConfigServer can be embedded to have forward compatible implementations.
type UnimplementedMetricConfigServer struct {
}

func (*UnimplementedMetricConfigServer) GetMetricConfig(ctx context.Context, req *MetricConfigRequest) (*MetricConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricConfig not implemented")
}

func RegisterMetricConfigServer(s *grpc.Server, srv MetricConfigServer) {
	s.RegisterService(&_MetricConfig_serviceDesc, srv)
}

func _MetricConfig_GetMetricConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricConfigServer).GetMetricConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.opentelemetry.proto.metrics.experimental.MetricConfig/GetMetricConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricConfigServer).GetMetricConfig(ctx, req.(*MetricConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetricConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.opentelemetry.proto.metrics.experimental.MetricConfig",
	HandlerType: (*MetricConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetricConfig",
			Handler:    _MetricConfig_GetMetricConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opentelemetry/proto/metrics/experimental/metrics_config_service.proto",
}
