#syntax=docker/dockerfile:1.2
FROM golang:1.19-alpine AS builder

RUN apk add git
RUN git clone --branch v1.41.0 --depth 1 https://github.com/jaegertracing/jaeger
WORKDIR /go/jaeger
COPY demo/hotrod.patch .
RUN git apply hotrod.patch
ENV CGO_ENABLED 0
RUN go install ./examples/hotrod

FROM scratch
USER 10001
COPY --from=builder --chmod=0755 /go/bin/hotrod /
ENTRYPOINT ["/hotrod"]
CMD ["all"]
