// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opentelemetry/proto/trace/v1/trace_config.proto

package v1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// How spans should be sampled:
// - Always off
// - Always on
// - Always follow the parent Span's decision (off if no parent).
type ConstantSampler_ConstantDecision int32

const (
	ConstantSampler_ALWAYS_OFF    ConstantSampler_ConstantDecision = 0
	ConstantSampler_ALWAYS_ON     ConstantSampler_ConstantDecision = 1
	ConstantSampler_ALWAYS_PARENT ConstantSampler_ConstantDecision = 2
)

var ConstantSampler_ConstantDecision_name = map[int32]string{
	0: "ALWAYS_OFF",
	1: "ALWAYS_ON",
	2: "ALWAYS_PARENT",
}

var ConstantSampler_ConstantDecision_value = map[string]int32{
	"ALWAYS_OFF":    0,
	"ALWAYS_ON":     1,
	"ALWAYS_PARENT": 2,
}

func (x ConstantSampler_ConstantDecision) String() string {
	return proto.EnumName(ConstantSampler_ConstantDecision_name, int32(x))
}

func (ConstantSampler_ConstantDecision) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5936aa8fa6443e6f, []int{1, 0}
}

// Global configuration of the trace service. All fields must be specified, or
// the default (zero) values will be used for each type.
type TraceConfig struct {
	// The global default sampler used to make decisions on span sampling.
	//
	// Types that are valid to be assigned to Sampler:
	//	*TraceConfig_ConstantSampler
	//	*TraceConfig_TraceIdRatioBased
	//	*TraceConfig_RateLimitingSampler
	Sampler isTraceConfig_Sampler `protobuf_oneof:"sampler"`
	// The global default max number of attributes per span.
	MaxNumberOfAttributes int64 `protobuf:"varint,4,opt,name=max_number_of_attributes,json=maxNumberOfAttributes,proto3" json:"max_number_of_attributes,omitempty"`
	// The global default max number of annotation events per span.
	MaxNumberOfTimedEvents int64 `protobuf:"varint,5,opt,name=max_number_of_timed_events,json=maxNumberOfTimedEvents,proto3" json:"max_number_of_timed_events,omitempty"`
	// The global default max number of attributes per timed event.
	MaxNumberOfAttributesPerTimedEvent int64 `protobuf:"varint,6,opt,name=max_number_of_attributes_per_timed_event,json=maxNumberOfAttributesPerTimedEvent,proto3" json:"max_number_of_attributes_per_timed_event,omitempty"`
	// The global default max number of link entries per span.
	MaxNumberOfLinks int64 `protobuf:"varint,7,opt,name=max_number_of_links,json=maxNumberOfLinks,proto3" json:"max_number_of_links,omitempty"`
	// The global default max number of attributes per span.
	MaxNumberOfAttributesPerLink int64    `protobuf:"varint,8,opt,name=max_number_of_attributes_per_link,json=maxNumberOfAttributesPerLink,proto3" json:"max_number_of_attributes_per_link,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *TraceConfig) Reset()         { *m = TraceConfig{} }
func (m *TraceConfig) String() string { return proto.CompactTextString(m) }
func (*TraceConfig) ProtoMessage()    {}
func (*TraceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5936aa8fa6443e6f, []int{0}
}
func (m *TraceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceConfig.Unmarshal(m, b)
}
func (m *TraceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceConfig.Marshal(b, m, deterministic)
}
func (m *TraceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceConfig.Merge(m, src)
}
func (m *TraceConfig) XXX_Size() int {
	return xxx_messageInfo_TraceConfig.Size(m)
}
func (m *TraceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TraceConfig proto.InternalMessageInfo

type isTraceConfig_Sampler interface {
	isTraceConfig_Sampler()
}

type TraceConfig_ConstantSampler struct {
	ConstantSampler *ConstantSampler `protobuf:"bytes,1,opt,name=constant_sampler,json=constantSampler,proto3,oneof" json:"constant_sampler,omitempty"`
}
type TraceConfig_TraceIdRatioBased struct {
	TraceIdRatioBased *TraceIdRatioBased `protobuf:"bytes,2,opt,name=trace_id_ratio_based,json=traceIdRatioBased,proto3,oneof" json:"trace_id_ratio_based,omitempty"`
}
type TraceConfig_RateLimitingSampler struct {
	RateLimitingSampler *RateLimitingSampler `protobuf:"bytes,3,opt,name=rate_limiting_sampler,json=rateLimitingSampler,proto3,oneof" json:"rate_limiting_sampler,omitempty"`
}

func (*TraceConfig_ConstantSampler) isTraceConfig_Sampler()     {}
func (*TraceConfig_TraceIdRatioBased) isTraceConfig_Sampler()   {}
func (*TraceConfig_RateLimitingSampler) isTraceConfig_Sampler() {}

func (m *TraceConfig) GetSampler() isTraceConfig_Sampler {
	if m != nil {
		return m.Sampler
	}
	return nil
}

func (m *TraceConfig) GetConstantSampler() *ConstantSampler {
	if x, ok := m.GetSampler().(*TraceConfig_ConstantSampler); ok {
		return x.ConstantSampler
	}
	return nil
}

func (m *TraceConfig) GetTraceIdRatioBased() *TraceIdRatioBased {
	if x, ok := m.GetSampler().(*TraceConfig_TraceIdRatioBased); ok {
		return x.TraceIdRatioBased
	}
	return nil
}

func (m *TraceConfig) GetRateLimitingSampler() *RateLimitingSampler {
	if x, ok := m.GetSampler().(*TraceConfig_RateLimitingSampler); ok {
		return x.RateLimitingSampler
	}
	return nil
}

func (m *TraceConfig) GetMaxNumberOfAttributes() int64 {
	if m != nil {
		return m.MaxNumberOfAttributes
	}
	return 0
}

func (m *TraceConfig) GetMaxNumberOfTimedEvents() int64 {
	if m != nil {
		return m.MaxNumberOfTimedEvents
	}
	return 0
}

func (m *TraceConfig) GetMaxNumberOfAttributesPerTimedEvent() int64 {
	if m != nil {
		return m.MaxNumberOfAttributesPerTimedEvent
	}
	return 0
}

func (m *TraceConfig) GetMaxNumberOfLinks() int64 {
	if m != nil {
		return m.MaxNumberOfLinks
	}
	return 0
}

func (m *TraceConfig) GetMaxNumberOfAttributesPerLink() int64 {
	if m != nil {
		return m.MaxNumberOfAttributesPerLink
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TraceConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TraceConfig_ConstantSampler)(nil),
		(*TraceConfig_TraceIdRatioBased)(nil),
		(*TraceConfig_RateLimitingSampler)(nil),
	}
}

// Sampler that always makes a constant decision on span sampling.
type ConstantSampler struct {
	Decision             ConstantSampler_ConstantDecision `protobuf:"varint,1,opt,name=decision,proto3,enum=internal.opentelemetry.proto.trace.v1.ConstantSampler_ConstantDecision" json:"decision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ConstantSampler) Reset()         { *m = ConstantSampler{} }
func (m *ConstantSampler) String() string { return proto.CompactTextString(m) }
func (*ConstantSampler) ProtoMessage()    {}
func (*ConstantSampler) Descriptor() ([]byte, []int) {
	return fileDescriptor_5936aa8fa6443e6f, []int{1}
}
func (m *ConstantSampler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantSampler.Unmarshal(m, b)
}
func (m *ConstantSampler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantSampler.Marshal(b, m, deterministic)
}
func (m *ConstantSampler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantSampler.Merge(m, src)
}
func (m *ConstantSampler) XXX_Size() int {
	return xxx_messageInfo_ConstantSampler.Size(m)
}
func (m *ConstantSampler) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantSampler.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantSampler proto.InternalMessageInfo

func (m *ConstantSampler) GetDecision() ConstantSampler_ConstantDecision {
	if m != nil {
		return m.Decision
	}
	return ConstantSampler_ALWAYS_OFF
}

// Sampler that tries to uniformly sample traces with a given ratio.
// The ratio of sampling a trace is equal to that of the specified ratio.
type TraceIdRatioBased struct {
	// The desired ratio of sampling. Must be within [0.0, 1.0].
	SamplingRatio        float64  `protobuf:"fixed64,1,opt,name=samplingRatio,proto3" json:"samplingRatio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceIdRatioBased) Reset()         { *m = TraceIdRatioBased{} }
func (m *TraceIdRatioBased) String() string { return proto.CompactTextString(m) }
func (*TraceIdRatioBased) ProtoMessage()    {}
func (*TraceIdRatioBased) Descriptor() ([]byte, []int) {
	return fileDescriptor_5936aa8fa6443e6f, []int{2}
}
func (m *TraceIdRatioBased) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceIdRatioBased.Unmarshal(m, b)
}
func (m *TraceIdRatioBased) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceIdRatioBased.Marshal(b, m, deterministic)
}
func (m *TraceIdRatioBased) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceIdRatioBased.Merge(m, src)
}
func (m *TraceIdRatioBased) XXX_Size() int {
	return xxx_messageInfo_TraceIdRatioBased.Size(m)
}
func (m *TraceIdRatioBased) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceIdRatioBased.DiscardUnknown(m)
}

var xxx_messageInfo_TraceIdRatioBased proto.InternalMessageInfo

func (m *TraceIdRatioBased) GetSamplingRatio() float64 {
	if m != nil {
		return m.SamplingRatio
	}
	return 0
}

// Sampler that tries to sample with a rate per time window.
type RateLimitingSampler struct {
	// Rate per second.
	Qps                  int64    `protobuf:"varint,1,opt,name=qps,proto3" json:"qps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateLimitingSampler) Reset()         { *m = RateLimitingSampler{} }
func (m *RateLimitingSampler) String() string { return proto.CompactTextString(m) }
func (*RateLimitingSampler) ProtoMessage()    {}
func (*RateLimitingSampler) Descriptor() ([]byte, []int) {
	return fileDescriptor_5936aa8fa6443e6f, []int{3}
}
func (m *RateLimitingSampler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimitingSampler.Unmarshal(m, b)
}
func (m *RateLimitingSampler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimitingSampler.Marshal(b, m, deterministic)
}
func (m *RateLimitingSampler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimitingSampler.Merge(m, src)
}
func (m *RateLimitingSampler) XXX_Size() int {
	return xxx_messageInfo_RateLimitingSampler.Size(m)
}
func (m *RateLimitingSampler) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimitingSampler.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimitingSampler proto.InternalMessageInfo

func (m *RateLimitingSampler) GetQps() int64 {
	if m != nil {
		return m.Qps
	}
	return 0
}

func init() {
	proto.RegisterEnum("internal.opentelemetry.proto.trace.v1.ConstantSampler_ConstantDecision", ConstantSampler_ConstantDecision_name, ConstantSampler_ConstantDecision_value)
	proto.RegisterType((*TraceConfig)(nil), "internal.opentelemetry.proto.trace.v1.TraceConfig")
	proto.RegisterType((*ConstantSampler)(nil), "internal.opentelemetry.proto.trace.v1.ConstantSampler")
	proto.RegisterType((*TraceIdRatioBased)(nil), "internal.opentelemetry.proto.trace.v1.TraceIdRatioBased")
	proto.RegisterType((*RateLimitingSampler)(nil), "internal.opentelemetry.proto.trace.v1.RateLimitingSampler")
}

func init() {
	proto.RegisterFile("opentelemetry/proto/trace/v1/trace_config.proto", fileDescriptor_5936aa8fa6443e6f)
}

var fileDescriptor_5936aa8fa6443e6f = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0xa1, 0xf9, 0x9a, 0x88, 0xc4, 0x2c, 0x4d, 0x65, 0x55, 0x3d, 0xa4, 0x56, 0xab, 0x72,
	0x89, 0xad, 0xa4, 0x52, 0x3f, 0x72, 0x83, 0x90, 0x8f, 0x4a, 0x88, 0x20, 0x07, 0xa9, 0x6a, 0x2f,
	0xab, 0xb5, 0xbd, 0xd0, 0x55, 0xec, 0x5d, 0x77, 0x3d, 0x20, 0x72, 0xef, 0xff, 0xe8, 0x1f, 0xe9,
	0x8f, 0xab, 0xbc, 0x10, 0x02, 0x24, 0xa9, 0x50, 0x6f, 0x33, 0xef, 0xe9, 0xbd, 0x37, 0x63, 0x8f,
	0x0d, 0xbe, 0xca, 0xb8, 0x44, 0x9e, 0xf0, 0x94, 0xa3, 0xbe, 0xf5, 0x33, 0xad, 0x50, 0xf9, 0xa8,
	0x59, 0xc4, 0xfd, 0xd1, 0xd1, 0xa4, 0xa0, 0x91, 0x92, 0x7d, 0x31, 0xf0, 0x0c, 0x47, 0xde, 0x0a,
	0x89, 0x5c, 0x4b, 0x96, 0x78, 0x0b, 0xca, 0x09, 0xeb, 0x19, 0x81, 0x37, 0x3a, 0x72, 0x7f, 0xaf,
	0xc3, 0x4e, 0xaf, 0x68, 0x4e, 0x8d, 0x98, 0x44, 0x60, 0x47, 0x4a, 0xe6, 0xc8, 0x24, 0xd2, 0x9c,
	0xa5, 0x59, 0xc2, 0xb5, 0x63, 0x1d, 0x58, 0xf5, 0x9d, 0xe3, 0x0f, 0xde, 0x4a, 0x8e, 0xde, 0xe9,
	0x54, 0x7e, 0x3d, 0x51, 0x5f, 0x96, 0x82, 0xbd, 0x68, 0x11, 0x22, 0x37, 0xf0, 0x7c, 0x32, 0xb1,
	0x88, 0xa9, 0x66, 0x28, 0x14, 0x0d, 0x59, 0xce, 0x63, 0x67, 0xcd, 0x04, 0x7d, 0x5a, 0x31, 0xc8,
	0x8c, 0xfd, 0x25, 0x0e, 0x0a, 0x83, 0x66, 0xa1, 0xbf, 0x2c, 0x05, 0x55, 0x5c, 0x06, 0x49, 0x06,
	0xfb, 0x9a, 0x21, 0xa7, 0x89, 0x48, 0x05, 0x0a, 0x39, 0x98, 0xad, 0x55, 0x36, 0x69, 0x27, 0x2b,
	0xa6, 0x05, 0x0c, 0x79, 0x7b, 0x6a, 0x71, 0xbf, 0x5a, 0x4d, 0x3f, 0x84, 0xc9, 0x47, 0x70, 0x52,
	0x36, 0xa6, 0x72, 0x98, 0x86, 0x5c, 0x53, 0xd5, 0xa7, 0x0c, 0x51, 0x8b, 0x70, 0x88, 0x3c, 0x77,
	0x9e, 0x1d, 0x58, 0xf5, 0x72, 0xb0, 0x9f, 0xb2, 0x71, 0xc7, 0xd0, 0x57, 0xfd, 0xc6, 0x8c, 0x24,
	0x27, 0xf0, 0x72, 0x51, 0x88, 0x22, 0xe5, 0x31, 0xe5, 0x23, 0x2e, 0x31, 0x77, 0xd6, 0x8d, 0xf4,
	0xc5, 0x9c, 0xb4, 0x57, 0xd0, 0x67, 0x86, 0x25, 0x3d, 0xa8, 0x3f, 0x15, 0x4a, 0x33, 0xae, 0xe7,
	0xad, 0x9c, 0x0d, 0xe3, 0xe4, 0x3e, 0x3a, 0x44, 0x97, 0xeb, 0x7b, 0x5b, 0x72, 0x08, 0xb5, 0x45,
	0xd7, 0x44, 0xc8, 0x9b, 0xdc, 0xd9, 0x34, 0x06, 0xf6, 0x9c, 0x41, 0xbb, 0xc0, 0xc9, 0x05, 0xbc,
	0xfe, 0xe7, 0x10, 0x85, 0xda, 0xd9, 0x32, 0xe2, 0x57, 0x4f, 0xa5, 0x17, 0x4e, 0xcd, 0x6d, 0xd8,
	0x9c, 0xbe, 0x26, 0xf7, 0x8f, 0x05, 0x7b, 0x4b, 0x37, 0x45, 0x22, 0xd8, 0x8a, 0x79, 0x24, 0x72,
	0xa1, 0xa4, 0xb9, 0xce, 0xdd, 0xe3, 0x8b, 0xff, 0xbb, 0xce, 0x59, 0xdf, 0x9a, 0xda, 0x05, 0x33,
	0x63, 0xb7, 0x05, 0xf6, 0x32, 0x4b, 0x76, 0x01, 0x1a, 0xed, 0xaf, 0x8d, 0x6f, 0xd7, 0xf4, 0xea,
	0xfc, 0xdc, 0x2e, 0x91, 0x0a, 0x6c, 0xdf, 0xf5, 0x1d, 0xdb, 0x22, 0x55, 0xa8, 0x4c, 0xdb, 0x6e,
	0x23, 0x38, 0xeb, 0xf4, 0xec, 0x35, 0xf7, 0x33, 0x54, 0x1f, 0x1c, 0x2a, 0x79, 0x03, 0x15, 0xb3,
	0x9e, 0x90, 0x03, 0x83, 0x9a, 0x25, 0xac, 0x60, 0x11, 0x74, 0xdf, 0x41, 0xed, 0x91, 0xab, 0x23,
	0x36, 0x94, 0x7f, 0x66, 0xb9, 0x91, 0x94, 0x83, 0xa2, 0x6c, 0xfe, 0xb2, 0xa0, 0x2e, 0xd4, 0x6a,
	0x4f, 0xa0, 0x69, 0xcf, 0x7d, 0xee, 0xdd, 0x82, 0xea, 0x5a, 0xdf, 0x5b, 0x03, 0x81, 0x3f, 0x86,
	0xa1, 0x17, 0xa9, 0xd4, 0x17, 0xb2, 0x9f, 0x0c, 0xc7, 0x31, 0x43, 0x76, 0x57, 0x86, 0x87, 0x2a,
	0xcc, 0xb9, 0x1e, 0xb1, 0x50, 0x24, 0x02, 0x6f, 0x7d, 0x85, 0x49, 0xe6, 0x47, 0x2a, 0x49, 0x78,
	0x84, 0x4a, 0xcf, 0xfe, 0x42, 0xe1, 0x86, 0x49, 0x7a, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xbd,
	0x7f, 0x1a, 0x23, 0xac, 0x04, 0x00, 0x00,
}
