---
name: "Semantic PR and Commit Messages"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  semantic:
    uses: jacobmarble/kiss-semantic/.github/workflows/semantic.yml@main
